import bestseller1 from "../IconsAndPhotos/bestseller1.png";
import bestseller2 from "../IconsAndPhotos/bestseller2.png";
import blueCircle from "../IconsAndPhotos/blueCircle.svg";
import greenCircle from "../IconsAndPhotos/greenCircle.svg";
import orangeCircle from "../IconsAndPhotos/orangeCircle.svg";
import blackCircle from "../IconsAndPhotos/blackCircle.svg";
import HomeToShop from "../IconsAndPhotos/HomeToShop.svg";
import ProductTopImg from "../IconsAndPhotos/ProductTopImg.png";
import viewBox from "../IconsAndPhotos/viewBox.png";
import viewList from "../IconsAndPhotos/viewList.png";
import filterButton from "../IconsAndPhotos/filterButton.png";
import brands1 from "../IconsAndPhotos/fa-brands-1.png";
import brands2 from "../IconsAndPhotos/fa-brands-2.png";
import brands3 from "../IconsAndPhotos/fa-brands-3.png";
import brands4 from "../IconsAndPhotos/fa-brands-4.png";
import brands5 from "../IconsAndPhotos/fa-brands-5.png";
import brands6 from "../IconsAndPhotos/fa-brands-6.svg";

export const Pdata = {
  headerArea: {
    ProductTopImg,
    viewBox,
    viewList,
    filterButton,
  },
  bodyArea: {
    HomeToShop,
    productCarsdArray: [
      {
        id: "1",
        img: bestseller1,
        tittle: "Graphic Design",
        descripton: "English department",
        price1: "$16.48",
        price2: "$6.48",
        color1: blueCircle,
        color2: greenCircle,
        color3: orangeCircle,
        color4: blackCircle,
      },
      {
        id: "2",
        img: bestseller2,
        tittle: "Graphic Design",
        descripton: "English department",
        price1: "$16.48",
        price2: "$6.48",
        color1: blueCircle,
        color2: greenCircle,
        color3: orangeCircle,
        color4: blackCircle,
      },
      {
        id: "1",
        img: bestseller1,
        tittle: "Graphic Design",
        descripton: "English department",
        price1: "$16.48",
        price2: "$6.48",
        color1: blueCircle,
        color2: greenCircle,
        color3: orangeCircle,
        color4: blackCircle,
      },
      {
        id: "2",
        img: bestseller2,
        tittle: "Graphic Design",
        descripton: "English department",
        price1: "$16.48",
        price2: "$6.48",
        color1: blueCircle,
        color2: greenCircle,
        color3: orangeCircle,
        color4: blackCircle,
      },
      {
        id: "1",
        img: bestseller1,
        tittle: "Graphic Design",
        descripton: "English department",
        price1: "$16.48",
        price2: "$6.48",
        color1: blueCircle,
        color2: greenCircle,
        color3: orangeCircle,
        color4: blackCircle,
      },
      {
        id: "2",
        img: bestseller2,
        tittle: "Graphic Design",
        descripton: "English department",
        price1: "$16.48",
        price2: "$6.48",
        color1: blueCircle,
        color2: greenCircle,
        color3: orangeCircle,
        color4: blackCircle,
      },
      {
        id: "1",
        img: bestseller1,
        tittle: "Graphic Design",
        descripton: "English department",
        price1: "$16.48",
        price2: "$6.48",
        color1: blueCircle,
        color2: greenCircle,
        color3: orangeCircle,
        color4: blackCircle,
      },
      {
        id: "2",
        img: bestseller2,
        tittle: "Graphic Design",
        descripton: "English department",
        price1: "$16.48",
        price2: "$6.48",
        color1: blueCircle,
        color2: greenCircle,
        color3: orangeCircle,
        color4: blackCircle,
      },
      {
        id: "1",
        img: bestseller1,
        tittle: "Graphic Design",
        descripton: "English department",
        price1: "$16.48",
        price2: "$6.48",
        color1: blueCircle,
        color2: greenCircle,
        color3: orangeCircle,
        color4: blackCircle,
      },
      {
        id: "2",
        img: bestseller2,
        tittle: "Graphic Design",
        descripton: "English department",
        price1: "$16.48",
        price2: "$6.48",
        color1: blueCircle,
        color2: greenCircle,
        color3: orangeCircle,
        color4: blackCircle,
      },
      {
        id: "1",
        img: bestseller1,
        tittle: "Graphic Design",
        descripton: "English department",
        price1: "$16.48",
        price2: "$6.48",
        color1: blueCircle,
        color2: greenCircle,
        color3: orangeCircle,
        color4: blackCircle,
      },
      {
        id: "2",
        img: bestseller2,
        tittle: "Graphic Design",
        descripton: "English department",
        price1: "$16.48",
        price2: "$6.48",
        color1: blueCircle,
        color2: greenCircle,
        color3: orangeCircle,
        color4: blackCircle,
      },
      {
        id: "1",
        img: bestseller1,
        tittle: "Graphic Design",
        descripton: "English department",
        price1: "$16.48",
        price2: "$6.48",
        color1: blueCircle,
        color2: greenCircle,
        color3: orangeCircle,
        color4: blackCircle,
      },
      {
        id: "2",
        img: bestseller2,
        tittle: "Graphic Design",
        descripton: "English department",
        price1: "$16.48",
        price2: "$6.48",
        color1: blueCircle,
        color2: greenCircle,
        color3: orangeCircle,
        color4: blackCircle,
      },
      {
        id: "1",
        img: bestseller1,
        tittle: "Graphic Design",
        descripton: "English department",
        price1: "$16.48",
        price2: "$6.48",
        color1: blueCircle,
        color2: greenCircle,
        color3: orangeCircle,
        color4: blackCircle,
      },
      {
        id: "2",
        img: bestseller2,
        tittle: "Graphic Design",
        descripton: "English department",
        price1: "$16.48",
        price2: "$6.48",
        color1: blueCircle,
        color2: greenCircle,
        color3: orangeCircle,
        color4: blackCircle,
      },
    ],
  },
  footerArea: {
    brands1,
    brands2,
    brands3,
    brands4,
    brands5,
    brands6,
  },
};
