import bestseller1 from "../IconsAndPhotos/bestseller1.png";
import bestseller2 from "../IconsAndPhotos/bestseller2.png";
import blueCircle from "../IconsAndPhotos/blueCircle.svg";
import greenCircle from "../IconsAndPhotos/greenCircle.svg";
import orangeCircle from "../IconsAndPhotos/orangeCircle.svg";
import blackCircle from "../IconsAndPhotos/blackCircle.svg";

export const Pdata = {
  bodyArea: {
    productCarsdArray: [
      {
        id: "1",
        img: bestseller1,
        tittle: "Graphic Design",
        descripton: "English department",
        price1: "$16.48",
        price2: "$6.48",
        color1: blueCircle,
        color2: greenCircle,
        color3: orangeCircle,
        color4: blackCircle,
      },
      {
        id: "2",
        img: bestseller2,
        tittle: "Graphic Design",
        descripton: "English department",
        price1: "$16.48",
        price2: "$6.48",
        color1: blueCircle,
        color2: greenCircle,
        color3: orangeCircle,
        color4: blackCircle,
      },
      {
        id: "1",
        img: bestseller1,
        tittle: "Graphic Design",
        descripton: "English department",
        price1: "$16.48",
        price2: "$6.48",
        color1: blueCircle,
        color2: greenCircle,
        color3: orangeCircle,
        color4: blackCircle,
      },
      {
        id: "2",
        img: bestseller2,
        tittle: "Graphic Design",
        descripton: "English department",
        price1: "$16.48",
        price2: "$6.48",
        color1: blueCircle,
        color2: greenCircle,
        color3: orangeCircle,
        color4: blackCircle,
      },
      {
        id: "1",
        img: bestseller1,
        tittle: "Graphic Design",
        descripton: "English department",
        price1: "$16.48",
        price2: "$6.48",
        color1: blueCircle,
        color2: greenCircle,
        color3: orangeCircle,
        color4: blackCircle,
      },
      {
        id: "2",
        img: bestseller2,
        tittle: "Graphic Design",
        descripton: "English department",
        price1: "$16.48",
        price2: "$6.48",
        color1: blueCircle,
        color2: greenCircle,
        color3: orangeCircle,
        color4: blackCircle,
      },
      {
        id: "1",
        img: bestseller1,
        tittle: "Graphic Design",
        descripton: "English department",
        price1: "$16.48",
        price2: "$6.48",
        color1: blueCircle,
        color2: greenCircle,
        color3: orangeCircle,
        color4: blackCircle,
      },
      {
        id: "2",
        img: bestseller2,
        tittle: "Graphic Design",
        descripton: "English department",
        price1: "$16.48",
        price2: "$6.48",
        color1: blueCircle,
        color2: greenCircle,
        color3: orangeCircle,
        color4: blackCircle,
      },
      {
        id: "1",
        img: bestseller1,
        tittle: "Graphic Design",
        descripton: "English department",
        price1: "$16.48",
        price2: "$6.48",
        color1: blueCircle,
        color2: greenCircle,
        color3: orangeCircle,
        color4: blackCircle,
      },
      {
        id: "2",
        img: bestseller2,
        tittle: "Graphic Design",
        descripton: "English department",
        price1: "$16.48",
        price2: "$6.48",
        color1: blueCircle,
        color2: greenCircle,
        color3: orangeCircle,
        color4: blackCircle,
      },
      {
        id: "1",
        img: bestseller1,
        tittle: "Graphic Design",
        descripton: "English department",
        price1: "$16.48",
        price2: "$6.48",
        color1: blueCircle,
        color2: greenCircle,
        color3: orangeCircle,
        color4: blackCircle,
      },
      {
        id: "2",
        img: bestseller2,
        tittle: "Graphic Design",
        descripton: "English department",
        price1: "$16.48",
        price2: "$6.48",
        color1: blueCircle,
        color2: greenCircle,
        color3: orangeCircle,
        color4: blackCircle,
      },
      {
        id: "1",
        img: bestseller1,
        tittle: "Graphic Design",
        descripton: "English department",
        price1: "$16.48",
        price2: "$6.48",
        color1: blueCircle,
        color2: greenCircle,
        color3: orangeCircle,
        color4: blackCircle,
      },
      {
        id: "2",
        img: bestseller2,
        tittle: "Graphic Design",
        descripton: "English department",
        price1: "$16.48",
        price2: "$6.48",
        color1: blueCircle,
        color2: greenCircle,
        color3: orangeCircle,
        color4: blackCircle,
      },
      {
        id: "1",
        img: bestseller1,
        tittle: "Graphic Design",
        descripton: "English department",
        price1: "$16.48",
        price2: "$6.48",
        color1: blueCircle,
        color2: greenCircle,
        color3: orangeCircle,
        color4: blackCircle,
      },
      {
        id: "2",
        img: bestseller2,
        tittle: "Graphic Design",
        descripton: "English department",
        price1: "$16.48",
        price2: "$6.48",
        color1: blueCircle,
        color2: greenCircle,
        color3: orangeCircle,
        color4: blackCircle,
      },
    ],
  },
};
